// This file is generated by `node scripts/generate-extension-config.js` during
// the build process. Do **not** check real credentials into source control.
// Instead populate a `.env.local` (or similar) at the project root and rebuild.

window.firebaseConfig = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
  measurementId: "" // optional
};
